/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.ac.unpas.tubes.aut;

import dao.UserDao;
import java.util.UUID;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import user.User;
import id.ac.unpas.tubes.aut.Login;
import javax.swing.SwingUtilities;

/**
 *
 * @author ridho
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordError = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        regisAlamat = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regisBtn = new javax.swing.JButton();
        regisName = new javax.swing.JTextField();
        regisEmail = new javax.swing.JTextField();
        nameError = new java.awt.Label();
        pwError = new java.awt.Label();
        noTelpError = new java.awt.Label();
        alamatError = new java.awt.Label();
        regisPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        regisTelp = new javax.swing.JTextField();

        passwordError.setBackground(new java.awt.Color(0, 153, 153));
        passwordError.setForeground(new java.awt.Color(204, 0, 0));

        regisAlamat.setColumns(20);
        regisAlamat.setRows(5);
        regisAlamat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                regisAlamatInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(regisAlamat);

        jLabel5.setLabelFor(regisAlamat);
        jLabel5.setText("Alamat:");

        jLabel1.setText("Register");

        jLabel2.setLabelFor(regisName);
        jLabel2.setText("Name:");

        jLabel3.setLabelFor(regisTelp);
        jLabel3.setText("Password:");

        jLabel4.setLabelFor(regisEmail);
        jLabel4.setText("No Telp:");

        regisBtn.setText("Register");
        regisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisBtnActionPerformed(evt);
            }
        });

        regisName.setToolTipText("");
        regisName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                regisNameInputMethodTextChanged(evt);
            }
        });

        regisEmail.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                regisEmailInputMethodTextChanged(evt);
            }
        });

        nameError.setText("label1");
        nameError.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nameErrorPropertyChange(evt);
            }
        });

        pwError.setText("label2");

        noTelpError.setText("label3");

        alamatError.setText("label4");

        regisPassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                regisPasswordInputMethodTextChanged(evt);
            }
        });
        regisPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisPasswordActionPerformed(evt);
            }
        });

        jLabel6.setText("Email");

        javax.swing.GroupLayout passwordErrorLayout = new javax.swing.GroupLayout(passwordError);
        passwordError.setLayout(passwordErrorLayout);
        passwordErrorLayout.setHorizontalGroup(
            passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordErrorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordErrorLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(regisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passwordErrorLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(passwordErrorLayout.createSequentialGroup()
                        .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(regisName))
                            .addComponent(regisEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(regisTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(regisPassword, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTelpError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        passwordErrorLayout.setVerticalGroup(
            passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(regisName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(nameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordErrorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pwError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(noTelpError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(alamatError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passwordErrorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regisEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regisPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passwordErrorLayout.createSequentialGroup()
                                .addComponent(regisTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(passwordErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel4))))
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(regisBtn)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(passwordError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Metode untuk membersihkan input field setelah registrasi berhasil
    private void clearInputFields() {
        regisName.setText("");
        regisTelp.setText("");
        regisEmail.setText("");
        regisAlamat.setText("");
    }

    private void regisNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_regisNameInputMethodTextChanged
        // TODO add your handling code here:
//        // Validasi jika nama kosong
//        if (regisName.getText().isEmpty()) {
//            // Tampilkan pesan kesalahan jika nama kosong
//            nameError.setText("Nama harus diisi");
//        } else {
//            // Jika tidak ada kesalahan, hapus pesan kesalahan
//            nameError.setText("");
//        }
    }//GEN-LAST:event_regisNameInputMethodTextChanged

    private void regisEmailInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_regisEmailInputMethodTextChanged
        // TODO add your handling code here:
//        // Validasi jika nomor telepon kosong atau tidak valid
//        String telp = regisTelp.getText();
//        if (telp.isEmpty() || !telp.matches("\\d+")) {
//            // Tampilkan pesan kesalahan jika nomor telepon kosong atau tidak valid
//            telpError.setText("Nomor telepon tidak valid");
//        } else {
//            // Jika tidak ada kesalahan, hapus pesan kesalahan
//            telpError.setText("");
//        }
    }//GEN-LAST:event_regisEmailInputMethodTextChanged

    private void regisAlamatInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_regisAlamatInputMethodTextChanged
        // TODO add your handling code here:
//        // Validasi jika alamat kosong
//        if (regisAlamat.getText().isEmpty()) {
//            // Tampilkan pesan kesalahan jika alamat kosong
//            alamatError.setText("Alamat harus diisi");
//        } else {
//            // Jika tidak ada kesalahan, hapus pesan kesalahan
//            alamatError.setText("");
//        }
    }//GEN-LAST:event_regisAlamatInputMethodTextChanged

    private void regisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisBtnActionPerformed
        // TODO add your handling code here:

        // Ambil nilai dari komponen-komponen UI
        String nama = regisName.getText();
        String email = regisEmail.getText();
        String password = new String(regisPassword.getPassword());
        String telp = regisTelp.getText();
        String alamat = regisAlamat.getText();

        // Validasi data sebelum disimpan
        if (nama.isEmpty() || password.length() < 6 || telp.isEmpty() || !telp.matches("\\d+") || alamat.isEmpty()) {
            // Tampilkan pesan kesalahan jika ada validasi yang gagal
            JOptionPane.showMessageDialog(this, "Data yang dimasukkan tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buat objek User
        User newUser = new User();
        newUser.setUserName(nama);
        newUser.setUserEmail(email);
        newUser.setUserPassword(password);
        newUser.setUserTelp(telp);
        newUser.setUserAlamat(alamat);
        newUser.setIsAdmin(false);  // Atur sesuai kebutuhan

        // Panggil DAO untuk menyimpan data ke dalam database
        UserDao UserDao = new UserDao();
        int result = UserDao.insert(newUser);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil", "Success", JOptionPane.INFORMATION_MESSAGE);

            Login loginPanel = new Login();

            // Dapatkan frame yang terkait dengan komponen ini
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

            // Ganti panel konten pada frame dengan panel login
            frame.setContentPane(loginPanel);

            // Perbarui tampilan frame
            frame.revalidate();
            frame.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal", "Error", JOptionPane.ERROR_MESSAGE);

        }
        clearInputFields();
    }//GEN-LAST:event_regisBtnActionPerformed

    private void nameErrorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nameErrorPropertyChange
        // TODO add your handling code here:
        String nama = regisName.getText();

        if (nama.isEmpty()) {
            // Set teks pesan kesalahan sesuai dengan kondisi yang tidak valid
            nameError.setText("Nama tidak boleh kosong");
            nameError.setVisible(true);

            // Lakukan hal yang sama untuk komponen pesan kesalahan lainnya
            // ...
        } else {
            // Jika input valid, sembunyikan semua pesan kesalahan
            nameError.setVisible(false);
            alamatError.setVisible(false);

            // Lanjutkan dengan operasi lainnya
        }
    }//GEN-LAST:event_nameErrorPropertyChange

    private void regisPasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_regisPasswordInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_regisPasswordInputMethodTextChanged

    private void regisPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisPasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label alamatError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label nameError;
    private java.awt.Label noTelpError;
    private javax.swing.JPanel passwordError;
    private java.awt.Label pwError;
    private javax.swing.JTextArea regisAlamat;
    private javax.swing.JButton regisBtn;
    private javax.swing.JTextField regisEmail;
    private javax.swing.JTextField regisName;
    private javax.swing.JPasswordField regisPassword;
    private javax.swing.JTextField regisTelp;
    // End of variables declaration//GEN-END:variables
}
